### ISSUE TITLE
`Black` + `Isort` + `flake8` support

### ISSUE THREAD

**Issue by caniko** [SpikeInterface/spikeinterface#1349]
## black + isort
Code formatters that will run on commit, the commit will be blocked if there are logical errors in any of the files. This means the code would fail to run anyway

## flake8
Checks if the code is formatted in accordance with rules set on `pyproject.toml`. Will block the PR and/or CI/CD if there are rule violations. We can pick and choose what rules to ignore.

## Solution
Create a new branch `black+isort+flake8` for merging the PR (#1342), and keep merging old PRs into the master. Thanks to @CodyCBakerPhD for the input. Merge `black+isort+flake8` into `master` when there are no PRs with the old format left.

### PR challenges
TLDR: New PRs must use `black+isort+flake8` as reference. Old PRs must merge into master ASAP.

Make sure new PRs are developed on `black+isort+flake8` I would mention this in `CONTRIBUTE.md`; failing to do this, you will need to copy over the `pyproject.toml` and `.pre-commit-config.yaml` into your own PR branch, and run the formatter yourself (`pre-commit run --all-files`) just note that there is one file on examples that have weird characters that need to be removed from its comments; `black` considers these characters unsafe and will refuse to run in safe-mode (something we want it do, always).

**Comment by caniko** [comment]
[List of rules](https://flake8.pycqa.org/en/latest/user/error-codes.html) for flake8, please pick before proceeding.

**Comment by alejoe91** [comment]
Moving converatsion from #1342 here:

@CodyCBakerPhD: What about a manual workflow or a cron job that runs `black` and `isort` on master (main)? I think this would make everyone happy! So open PRs don't need to update all the time due to pre-commit CI and the main branch will (almost) always be clean.

**Comment by caniko** [comment]
@alejoe91 pre-commit is an optional module. It is only run if you run `pre-commit install` after `git clone`.

**Comment by CodyCBakerPhD** [comment]
> What about a manual workflow or a cron job that runs black and isort on master (main)? I think this would make everyone happy! So open PRs don't need to update all the time due to pre-commit CI and the main branch will (almost) always be clean.

I've done that before, will leave code below

One final point I will make before doing that is have formatted code prior to the time of review itself saves a lot of dev time. I can't even count the wasted hours over the years from myself and people reviewing my code across different repos telling me to re-order my imports and reformat various things. `pre-commit` is very fast and easy to setup when needed and is hardly even noticeable thereafter; the bot, even more so.


```YAML
name: Run pre-commit as a workflow

on:
  pull_request:  # change to schedule or push to main if you want

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set cache hash
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Cache pre-commit
      id: cache-pre-commit
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - if: steps.cache-pre-commit.outputs.cache-hit == false
      name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files || true # `|| true` to not fail when something requires changing
    - name: Commit files
      run: | # `|| true` below to skip if nothing changed from pre-commit
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "pre-commit" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}  # this needs to be set as a secret
        branch: ${{ github.head_ref }}
        force: true
```
